/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Detvirker: typeof import('./src/components/detvirker.vue')['default']
    KanbanBoard: typeof import('./src/components/KanbanBoard.vue')['default']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
    TaskColumn: typeof import('./src/components/TaskColumn.vue')['default']
  }
}
